// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A business plan generation AI agent.
 *
 * - generateBusinessPlan - A function that handles the business plan generation process.
 * - GenerateBusinessPlanInput - The input type for the generateBusinessPlan function.
 * - GenerateBusinessPlanOutput - The return type for the generateBusinessPlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBusinessPlanInputSchema = z.object({
  companyName: z.string().describe('The name of the company.'),
  companyDescription: z.string().describe('A brief description of the company and its mission.'),
  targetMarket: z.string().describe('The target market for the company.'),
  productOrService: z.string().describe('The product or service the company offers.'),
  competitiveAdvantages: z.string().describe('The company\u2019s competitive advantages.'),
});

export type GenerateBusinessPlanInput = z.infer<typeof GenerateBusinessPlanInputSchema>;

const GenerateBusinessPlanOutputSchema = z.object({
  executiveSummary: z.string().describe('A brief overview of the business plan.'),
  companyDescription: z.string().describe('A detailed description of the company.'),
  marketAnalysis: z.string().describe('An analysis of the target market.'),
  productsAndServices: z.string().describe('A detailed description of the products and services offered.'),
  marketingAndSalesStrategy: z.string().describe('The strategy for marketing and sales.'),
  managementTeam: z.string().describe('Information about the management team.'),
  financialPlan: z.string().describe('The financial projections for the business.'),
  fundingRequest: z.string().describe('Details of the funding required.'),
  appendix: z.string().describe('Supporting documents and information.'),
});

export type GenerateBusinessPlanOutput = z.infer<typeof GenerateBusinessPlanOutputSchema>;

export async function generateBusinessPlan(input: GenerateBusinessPlanInput): Promise<GenerateBusinessPlanOutput> {
  return generateBusinessPlanFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateBusinessPlanPrompt',
  input: {schema: GenerateBusinessPlanInputSchema},
  output: {schema: GenerateBusinessPlanOutputSchema},
  prompt: `You are an expert business plan writer. Based on the information provided, create a comprehensive business plan with the following sections:

  1.  Executive Summary: A brief overview of the business plan.
  2.  Company Description: A detailed description of the company, its mission, and its vision.
  3.  Market Analysis: An analysis of the target market, including market size, trends, and competition.
  4.  Products and Services: A detailed description of the products and services offered by the company.
  5.  Marketing and Sales Strategy: The strategy for marketing and selling the company's products or services.
  6.  Management Team: Information about the management team, including their experience and qualifications.
  7.  Financial Plan: The financial projections for the business, including revenue forecasts, expense budgets, and cash flow statements.
  8.  Funding Request: Details of the funding required, including the amount of funding needed and how it will be used.
  9.  Appendix: Supporting documents and information.

  Use the following information to create the business plan:

  Company Name: {{{companyName}}}
  Company Description: {{{companyDescription}}}
  Target Market: {{{targetMarket}}}
  Product or Service: {{{productOrService}}}
  Competitive Advantages: {{{competitiveAdvantages}}}
  `,
});

const generateBusinessPlanFlow = ai.defineFlow(
  {
    name: 'generateBusinessPlanFlow',
    inputSchema: GenerateBusinessPlanInputSchema,
    outputSchema: GenerateBusinessPlanOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
